shell = python3 mc_pi.py 10000 $(seed) $(Cluster)

output              = run_$(Cluster)/logs/logs/job_$(Process).out
error               = run_$(Cluster)/logs/logs/job_$(Process).err
log                 = run_$(Cluster)/logs/logs/mc_pi.log

transfer_input_files  = mc_pi.py
transfer_output_files = output_$(seed).txt
transfer_output_remaps = "output_$(seed).txt = run_$(Cluster)/logs/output_$(seed).txt"

request_cpus        = 1
request_memory      = 512MB
request_disk        = 100MB

queue seed from seed_table.txt
